# Generated by Django 2.2 on 2021-02-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phno', models.CharField(max_length=15, unique=True)),
                ('role', models.CharField(max_length=60)),
                ('about', models.CharField(blank=True, max_length=60)),
                ('location', models.CharField(max_length=62)),
            ],
        ),
    ]
